import { useState, type ReactNode } from 'react'
import { Icon } from './Icon'
import { Avatar, RoomPlan, StatusBadge } from './BuildingView'
import { STATUS, TRADES, UNITS, draftReport, stats, unitStatus, type Action, type DemoState, type Task, type Trade, type WorkStatus } from './model'

export type Act = (action: Action) => boolean
export function SectionTitle({ eyebrow, title, text, children }: { eyebrow: string; title: string; text: string; children?: ReactNode }) {
  return <div className="st-page-heading"><div><span className="st-eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>{children}</div>
}
export function WorkPage({ state, openTask, createTask }: { state: DemoState; openTask: (task: Task) => void; createTask: () => void }) {
  const [trade, setTrade] = useState(''), [floor, setFloor] = useState('3'), [query, setQuery] = useState('')
  const tasks = state.tasks.filter(t => (!trade || t.trade === trade) && (!floor || t.unit.startsWith(floor)) && `${t.title} ${t.unit} ${TRADES[t.trade].company}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="st-page"><SectionTitle eyebrow="PLAN & COORDINATE" title="Good work starts with a clear plan." text="The right crew, in the right room, with a shared definition of done."><button className="st-primary" onClick={createTask}><Icon name="plus" size={16} />Assign work</button></SectionTitle><div className="st-filters"><div className="st-input-icon"><Icon name="search" size={16} /><input placeholder="Find work or a room…" aria-label="Find work" value={query} onChange={e => setQuery(e.target.value)} /></div><select aria-label="Work floor" value={floor} onChange={e => setFloor(e.target.value)}><option value="">All levels</option>{[1, 2, 3, 4, 5, 6].map(f => <option key={f} value={f}>Level {String(f).padStart(2, '0')}</option>)}</select><select aria-label="Work trade" value={trade} onChange={e => setTrade(e.target.value)}><option value="">All trades</option>{Object.entries(TRADES).map(([k, v]) => <option value={k} key={k}>{v.name}</option>)}</select><span>{tasks.length} work packages</span></div>
    <div className="st-board">{(['planned', 'active', 'blocked', 'review', 'approved'] as WorkStatus[]).map(status => <section className="st-board-column" key={status}><h3><i style={{ background: STATUS[status].color }} />{STATUS[status].label}<span>{tasks.filter(t => t.status === status).length}</span></h3>{tasks.filter(t => t.status === status).map(t => <button key={t.id} className="st-task-card" onClick={() => openTask(t)}><span className="st-task-trade" style={{ color: TRADES[t.trade].color }}>{TRADES[t.trade].name.toUpperCase()}</span><strong>{t.title}</strong><span className="st-task-location"><Icon name="pin" size={13} />Unit {t.unit} · Level {t.unit[0]}</span>{t.note && <p>{t.note}</p>}<div className="st-task-card-bottom"><span><Icon name="clock" size={13} />{formatDate(t.due)}</span><span>{t.evidence.length > 0 && <><Icon name="camera" size={13} />{t.evidence.length}</>}<Avatar trade={t.trade} small /></span></div></button>)}{!tasks.some(t => t.status === status) && <div className="st-column-empty">No work here</div>}</section>)}</div>
  </div>
}
export function EvidencePage({ state, act, openTask }: { state: DemoState; act: Act; openTask: (t: Task) => void }) {
  const [selected, setSelected] = useState('T-304-electrical'), [trade, setTrade] = useState('')
  const pending = state.tasks.filter(t => t.status === 'review' && (!trade || t.trade === trade))
  const task = pending.find(t => t.id === selected) || pending[0]
  const evidence = task ? state.evidence.filter(e => task.evidence.includes(e.id)) : []
  const issue = state.issues.find(i => i.task === task?.id && !i.resolved)
  const [fullImage, setFullImage] = useState<string | null>(null)
  return <div className="st-page"><SectionTitle eyebrow="EVIDENCE INBOX" title="A clear record. A confident decision." text="Review the evidence before approving the work. Every decision stays in the timeline."><span className="st-pill amber">{pending.length} awaiting review</span></SectionTitle>
    <div className="st-evidence-layout"><aside className="st-review-list"><div className="st-review-list-head"><strong>Submitted work</strong><select aria-label="Evidence trade" value={trade} onChange={e => setTrade(e.target.value)}><option value="">All trades</option>{Object.entries(TRADES).map(([k, v]) => <option key={k} value={k}>{v.name}</option>)}</select></div>{pending.map(t => <button className={task?.id === t.id ? 'active' : ''} key={t.id} onClick={() => setSelected(t.id)}><Avatar trade={t.trade} /><span><strong>Unit {t.unit} <small>{TRADES[t.trade].name}</small></strong><span>{t.title}</span><small>{TRADES[t.trade].person} · {t.evidence.length} attachment{t.evidence.length === 1 ? '' : 's'}</small></span><Icon name="chevron" size={14} /></button>)}{!pending.length && <div className="st-empty"><Icon name="check" size={32} /><h3>All caught up</h3><p>New submissions will appear here.</p></div>}</aside>
      <div className="st-review-detail">{task ? <><div className="st-review-title"><div><span className="st-eyebrow">UNIT {task.unit} / LEVEL {task.unit[0]}</span><h3>{task.title}</h3></div><StatusBadge status="review" /></div>{evidence.map(e => <div key={e.id} className="st-evidence-item"><button className="st-evidence-image" onClick={() => setFullImage(e.image)} aria-label="Enlarge evidence"><img src={e.image} alt={`${TRADES[task.trade].name} evidence for Unit ${task.unit}`} /><span><Icon name="expand" size={14} />View full image</span></button><div className="st-photo-meta"><span><Icon name="camera" size={14} />{e.kind === 'sample' ? 'Illustrative sample · not a site photograph' : 'Uploaded photo · saved on this device'}</span><span>{formatDate(e.at)}</span></div><div className="st-field-note"><Avatar trade={task.trade} /><div><strong>{e.author}<span>{TRADES[task.trade].company}</span></strong><p>{e.note}</p></div></div></div>)}<div className="st-review-guidance"><Icon name="shield" size={20} /><div><strong>Check the work, not just the photo.</strong><p>Confirm the location, visible work, and required records. This demo does not run an AI inspection or certify an installation.</p></div></div>{issue && <div className="st-callout danger"><Icon name="alert" /><div><strong>{issue.title}</strong><p>Resolve the linked issue before approval.</p><button onClick={() => openTask(task)}>Open issue & evidence <Icon name="arrow" size={14} /></button></div></div>}<div className="st-review-actions"><button className="st-secondary" onClick={() => openTask(task)}>Request changes</button><button className="st-primary" disabled={!!issue} onClick={() => act({ type: 'approve', task: task.id })}><Icon name="check" size={16} />Approve with evidence</button></div></> : <div className="st-empty st-large"><Icon name="shield" size={50} /><h3>Every decision, backed by evidence.</h3><p>Submit a field update to try the review workflow.</p></div>}</div></div>
    {fullImage && <div className="st-modal-backdrop" onClick={() => setFullImage(null)}><div className="st-lightbox"><button className="st-icon-btn" aria-label="Close full image" onClick={() => setFullImage(null)}><Icon name="close" /></button><img src={fullImage} alt="Full evidence attachment" /></div></div>}
  </div>
}
export function HandoffPage({ state, act, selectUnit }: { state: DemoState; act: Act; selectUnit: (id: string) => void }) {
  const [filter, setFilter] = useState('all'), [floor, setFloor] = useState('')
  const units = UNITS.filter(u => (!floor || u.floor === +floor) && (filter === 'all' || (filter === 'released' ? state.handoffs.includes(u.id) : unitStatus(state, u.id) === filter)))
  const n = stats(state)
  return <div className="st-page"><SectionTitle eyebrow="TRADE HANDOFFS" title="The next crew should never have to guess." text="Plumbing, electrical, ventilation, and inspection approvals determine room readiness." /><div className="st-handoff-summary"><div><Icon name="check" /><strong>{n.ready}</strong><span>rooms meet prerequisites</span></div><div><Icon name="handoff" /><strong>{state.handoffs.length}</strong><span>released to Interior Works</span></div><div><Icon name="alert" /><strong>{UNITS.filter(u => unitStatus(state, u.id) === 'blocked').length}</strong><span>blocked rooms</span></div></div><div className="st-filters"><div className="st-segment">{[['all', 'All rooms'], ['approved', 'Ready'], ['blocked', 'Blocked'], ['released', 'Released']].map(([k, label]) => <button className={filter === k ? 'active' : ''} key={k} onClick={() => setFilter(k)}>{label}</button>)}</div><select aria-label="Handoff floor" value={floor} onChange={e => setFloor(e.target.value)}><option value="">All levels</option>{[1, 2, 3, 4, 5, 6].map(f => <option key={f} value={f}>Level {f}</option>)}</select><span>{units.length} rooms</span></div><div className="st-room-grid">{units.map(u => {
    const status = unitStatus(state, u.id), released = state.handoffs.includes(u.id), tasks = state.tasks.filter(t => t.unit === u.id)
    return <article className="st-room-card" key={u.id}><div><span className="st-eyebrow">LEVEL {String(u.floor).padStart(2, '0')}</span><StatusBadge status={status} /></div><button className="st-room-card-title" onClick={() => selectUnit(u.id)}>Unit {u.id}<Icon name="arrow" size={17} /></button><p>{u.name} · {u.area} m²</p><div className="st-handoff-checks">{(Object.keys(TRADES) as Trade[]).map(trade => { const done = tasks.filter(t => t.trade === trade).every(t => t.status === 'approved'); return <span key={trade} className={done ? 'done' : ''} title={TRADES[trade].name}><Icon name={done ? 'check' : 'clock'} size={13} />{TRADES[trade].name}</span> })}</div><button className={released ? 'st-released' : 'st-secondary st-full'} disabled={status !== 'approved' || released} onClick={() => act({ type: 'handoff', unit: u.id })}><Icon name={released ? 'check' : 'handoff'} size={15} />{released ? 'Released to drywall' : status === 'approved' ? 'Release to drywall' : 'Awaiting prerequisites'}</button></article>
  })}</div>{!units.length && <div className="st-empty"><Icon name="handoff" size={32} /><h3>No rooms match these filters</h3><button onClick={() => { setFilter('all'); setFloor('') }}>Show all rooms</button></div>}</div>
}
export function ReportPage({ state, act }: { state: DemoState; act: Act }) {
  const [text, setText] = useState(state.report.text)
  const sign = () => act({ type: 'report', text, sign: true })
  const draft = () => { const body = draftReport(state); if (act({ type: 'report', text: body, sign: false })) setText(body) }
  const exportReport = () => { const url = URL.createObjectURL(new Blob([`${text}${state.report.signedAt ? `\n\nSigned by Sarah Mitchell · ${new Date(state.report.signedAt).toLocaleString()}` : '\n\nDRAFT — NOT SIGNED'}`], { type: 'text/plain' })); const a = document.createElement('a'); a.href = url; a.download = 'hawthorne-daily-report.txt'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }
  return <div className="st-page"><SectionTitle eyebrow="DAILY REPORT" title="The day’s work, already in one place." text="A draft compiled from your project records. Review, edit, and sign when it’s ready."><button className="st-secondary" onClick={exportReport} disabled={!text}><Icon name="download" size={16} />Export report</button></SectionTitle><div className="st-report-layout"><div className="st-report-paper"><div className="st-report-letterhead"><div className="st-mark"><Icon name="layers" size={24} /></div><div><strong>THE HAWTHORNE</strong><span>Daily construction report</span></div><span className={`st-pill ${state.report.signedAt ? 'green' : ''}`}>{state.report.signedAt ? 'Signed' : 'Draft'}</span></div>{!text ? <div className="st-empty st-large"><Icon name="report" size={46} /><h3>Your daily report starts with the work.</h3><p>Compile approved work, outstanding issues, and recorded activity into an editable draft.</p><button className="st-primary" onClick={draft}><Icon name="spark" size={16} />Draft from project records</button></div> : <><textarea aria-label="Daily report body" className="st-report-editor" value={text} onChange={e => setText(e.target.value)} readOnly={!!state.report.signedAt} /><div className="st-report-signature">{state.report.signedAt ? <><Icon name="lock" size={17} /><span>Signed by Sarah Mitchell<br /><small>{new Date(state.report.signedAt).toLocaleString()} · Record locked</small></span></> : <><p>Reviewed by the superintendent before sharing.</p><button className="st-secondary" onClick={() => act({ type: 'report', text, sign: false })}>Save draft</button><button className="st-primary" onClick={sign}><Icon name="check" size={16} />Sign report</button></>}</div></>}</div><aside className="st-report-sources"><div className="st-section-heading"><h3>Connected to the source</h3><Icon name="link" size={17} /></div><p>Every summary starts with recorded activity. This preview uses a deterministic template, not a live AI model.</p>{state.events.slice(0, 6).map(e => <div className="st-source" key={e.id}><Icon name="activity" size={15} /><div><strong>{e.title}</strong><span>{e.detail}</span><small>{e.actor}</small></div></div>)}<div className="st-callout"><Icon name="shield" size={18} /><p>Unrecorded weather, crew counts, and site conditions are never filled in automatically.</p></div>{text && !state.report.signedAt && <button className="st-secondary st-full" onClick={draft}><Icon name="reset" size={15} />Refresh from latest records</button>}</aside></div></div>
}
export function ActivityPage({ state, openTask }: { state: DemoState; openTask: (t: Task) => void }) {
  const [query, setQuery] = useState('')
  const events = state.events.filter(e => `${e.title} ${e.detail} ${e.actor}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="st-page"><SectionTitle eyebrow="PROJECT TIMELINE" title="Every update has a place in the story." text="Assignments, evidence, approvals, and handoffs—recorded as they happen." /><div className="st-input-icon st-activity-search"><Icon name="search" size={16} /><input placeholder="Search the timeline…" aria-label="Search timeline" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="st-timeline">{events.map(e => <article key={e.id}><div className="st-timeline-dot"><Icon name={e.title.includes('approved') ? 'check' : e.title.includes('released') ? 'handoff' : e.title.includes('Evidence') ? 'camera' : 'activity'} size={17} /></div><div><div className="st-timeline-title"><strong>{e.title}</strong><time>{new Date(e.at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div><p>{e.detail}</p><small>{e.actor} · {formatDate(e.at)}</small>{e.task && <button className="st-text-btn" onClick={() => { const task = state.tasks.find(t => t.id === e.task); if (task) openTask(task) }}>View work package <Icon name="arrow" size={13} /></button>}</div></article>)}</div>{!events.length && <div className="st-empty">No activity matches this search.</div>}</div>
}
export function FieldPage({ state, openTask, capture }: { state: DemoState; openTask: (t: Task) => void; capture: (t: Task) => void }) {
  const [trade, setTrade] = useState<Trade>('plumbing'), [floor, setFloor] = useState('3')
  const tasks = state.tasks.filter(t => t.trade === trade && t.status !== 'approved' && (!floor || t.unit.startsWith(floor)))
  return <div className="st-page st-field-page"><SectionTitle eyebrow="FIELD WORKSPACE" title="Less paperwork. More progress." text="Your rooms, your work, and one simple way to update the team." /><div className="st-field-shell"><div className="st-field-profile"><Avatar trade={trade} /><div><span>Good morning, {TRADES[trade].person.split(' ')[0]}.</span><h3>Let’s move the site forward.</h3><small>{TRADES[trade].company} · The Hawthorne</small></div><Icon name="sun" size={27} /></div><div className="st-filters"><select aria-label="Field crew" value={trade} onChange={e => setTrade(e.target.value as Trade)}>{Object.entries(TRADES).map(([k, v]) => <option key={k} value={k}>{v.person} · {v.name}</option>)}</select><select aria-label="Field floor" value={floor} onChange={e => setFloor(e.target.value)}><option value="">All levels</option>{[1, 2, 3, 4, 5, 6].map(f => <option key={f} value={f}>Level {f}</option>)}</select></div><div className="st-field-local"><Icon name="phone" size={16} /><span>Demo mode · updates are saved on this device, including while offline.</span></div><div className="st-section-heading"><h3>Your work packages</h3><span>{tasks.length} remaining</span></div>{tasks.map(t => <article className="st-field-task" key={t.id}><div className="st-field-room-plan"><RoomPlan selected={t.unit} status={t.status} /></div><div className="st-field-task-body"><div><span className="st-eyebrow">LEVEL {t.unit[0]} / UNIT {t.unit}</span><StatusBadge status={t.status} /></div><h3>{t.title}</h3><p>{t.note || (t.status === 'blocked' ? 'A required record is missing. Add correction evidence for the superintendent.' : 'Capture a full view and a clear connection detail. Add the required test record where applicable.')}</p><div><button className="st-secondary" onClick={() => openTask(t)}>View details</button><button className="st-primary" onClick={() => capture(t)}><Icon name="camera" size={16} />{t.status === 'review' ? 'Add evidence' : 'Post update'}</button></div></div></article>)}{!tasks.length && <div className="st-empty"><Icon name="check" size={36} /><h3>All work approved on this level.</h3><p>Choose another floor to see what’s next.</p></div>}</div></div>
}
export function formatDate(value: string) { return new Date(value.length === 10 ? `${value}T12:00:00` : value).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) }
