// Generated by scripts/generate_agent_types.py; do not edit by hand.

export type CheckResult = {
  id: string;
  check_code: string;
  check_version: string;
  element_ids: (string)[];
  outcome: 'pass' | 'potential_discrepancy' | 'insufficient_evidence' | 'unsupported' | 'failed';
  observation: string;
  evidence_ids: (string)[];
  sources: (SourceRef)[];
  limitations: (string)[];
  completion_eligible: boolean;
};

export type DailySummary = {
  project_id: string;
  date: string;
  timezone: string;
  status: 'available' | 'unavailable' | 'stale';
  generated_at: string | null;
  partial_history: boolean;
  statements: (SummaryStatement)[];
  reason: string | null;
};

export type Decision = {
  id: string;
  action_id: string;
  actor_id: string;
  decision: 'accept' | 'reject';
  reason: string;
  created_at: string;
  action: ProposedAction;
};

export type DecisionCreate = {
  decision: 'accept' | 'reject';
  expected_revision: number;
  fingerprint: string;
  reason: string;
};

export type Error = {
  code: 'unauthenticated' | 'forbidden' | 'not_found' | 'stale_revision' | 'superseded' | 'idempotency_conflict' | 'invalid_input' | 'rate_limited' | 'provider_unavailable' | 'unsupported_check' | 'analysis_failed';
  message: string;
};

export type ProposedAction = {
  id: string;
  kind: 'record_progress' | 'request_evidence' | 'open_review';
  status: 'proposed' | 'applied' | 'rejected' | 'superseded' | 'failed';
  expected_revision: number;
  fingerprint: string;
  check_ids: (string)[];
  element_ids: (string)[];
  description: string;
  requires_review: boolean;
};

export type Run = {
  id: string;
  project_id: string;
  upload_id: string;
  model_version_id: string;
  status: 'queued' | 'running' | 'awaiting_review' | 'completed' | 'failed' | 'cancelled' | 'superseded';
  created_at: string;
  updated_at: string;
  policy_version: string;
  prompt_version: string;
  model: string | null;
  sources: (SourceRef)[];
  checks: (CheckResult)[];
  actions: (ProposedAction)[];
  error: Error | null;
};

export type RunCreate = {
  upload_id: string;
  model_version_id: string;
};

export type SourceRef = {
  kind: 'drawing' | 'specification' | 'approved_change' | 'model' | 'event';
  id: string;
  revision: string;
  locator: string | null;
  sha256: string;
};

export type Suggestion = {
  text: string;
  reason: string;
  element_ids: (string)[];
  sources: (SourceRef)[];
};

export type SuggestionCreate = {
  kind: 'note' | 'location' | 'evidence_request';
  input_revision: string;
  text: string;
  model_version_id: string;
  element_ids: (string)[];
};

export type SuggestionResult = {
  input_revision: string;
  status: 'available' | 'unavailable';
  reason: string | null;
  suggestions: (Suggestion)[];
};

export type SummaryRefresh = {
  date: string;
  timezone: string;
};

export type SummaryStatement = {
  text: string;
  event_ids: (number)[];
  run_ids: (string)[];
};

export type VoiceCorrection = {
  text: string;
  expected_revision: number;
};

export type VoiceCreate = {
  zone_id: string;
  trade: string;
  filename: string;
  mime_type: 'audio/wav' | 'audio/mpeg' | 'audio/m4a' | 'audio/mp4' | 'audio/ogg' | 'audio/webm';
  captured_at: string | null;
  audio_base64: string;
};

export type VoiceNote = {
  id: string;
  project_id: string;
  actor_id: string;
  zone_id: string;
  trade: string;
  filename: string;
  mime_type: string;
  captured_at: string | null;
  created_at: string;
  status: 'queued' | 'running' | 'completed' | 'failed';
  original_text: string | null;
  text: string | null;
  revision: number;
  model: string | null;
  original_url: string;
  error: Error | null;
};
