"""Generate web DTOs from the backend models checked against contracts/openapi.yaml."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.agent.schemas import (
    DailySummary,
    Decision,
    DecisionCreate,
    Run,
    RunCreate,
    SuggestionCreate,
    SuggestionResult,
    SummaryRefresh,
    VoiceCorrection,
    VoiceCreate,
    VoiceNote,
)


def ts(schema):
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "anyOf" in schema:
        return " | ".join(ts(s) for s in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(repr(v) for v in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"({ts(schema['items'])})[]"
    if kind == "object":
        required = schema.get("required", [])
        return "{\n" + "\n".join(f"  {name}{'' if name in required else '?'}: {ts(value)};"
                                   for name, value in schema.get("properties", {}).items()) + "\n}"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}[kind]


schemas = {}
for model in (Run, RunCreate, Decision, DecisionCreate, SuggestionCreate, SuggestionResult, DailySummary,
              SummaryRefresh, VoiceCreate, VoiceCorrection, VoiceNote):
    schema = model.model_json_schema()
    schemas.update(schema.pop("$defs", {}))
    schemas[model.__name__] = schema
target = ROOT / "web/src/api/agent.generated.ts"
target.write_text("// Generated by scripts/generate_agent_types.py; do not edit by hand.\n\n"
                  + "\n\n".join(f"export type {name} = {ts(schema)};" for name, schema in sorted(schemas.items())) + "\n")
print(f"Generated {len(schemas)} agent DTOs")
