import { readFileSync } from "node:fs";
import { cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import type { ModelDataset } from "../viewer/modelData";
import Workspace from "../workspace/Workspace";
import { projectStorageKey } from "../workspace/projectState";

const model = JSON.parse(readFileSync("public/bim-duplex/model.json", "utf8")) as ModelDataset;
vi.mock("../viewer/modelData", async original => ({ ...await original<typeof import("../viewer/modelData")>(), loadDemoModel: async () => model }));
vi.mock("../workspace/BuildingCanvas", () => ({ default: () => <div data-testid="shared-building" /> }));
beforeEach(() => localStorage.clear());
afterEach(() => { cleanup(); localStorage.clear(); });

it("confirms a calendar-backed assignment, schedules an in-app follow-up and persists an actual reply", async () => {
  render(<MemoryRouter initialEntries={["/?panel=record&work=PLAN-401"]}><Workspace /></MemoryRouter>);
  await screen.findByRole("complementary", { name: "Work record" });
  const copilot = within(screen.getByRole("region", { name: "Project Copilot" }));
  fireEvent.click(copilot.getByRole("button", { name: "Open Project Copilot" }));
  fireEvent.click(copilot.getByRole("button", { name: "Assign" }));
  const form = within(copilot.getByRole("region", { name: "Coordinate work" }));
  expect(form.getByLabelText("Work")).toHaveValue("PLAN-401");
  expect(form.getByLabelText("Responsible person")).toHaveValue("Apex Mechanical · Marco Rossi");
  expect(form.getByRole("button", { name: "Review assignment" })).toBeDisabled();
  fireEvent.click(form.getByLabelText("I confirm this person is qualified for this work."));
  fireEvent.change(form.getByLabelText("Task instruction"), { target: { value: "Install radiator after framing confirms access" } });
  fireEvent.change(form.getByLabelText("Prerequisites"), { target: { value: "Framing lead confirms access" } });
  fireEvent.click(form.getByText("Connect calendar export"));
  fireEvent.click(form.getByLabelText("The export includes all commitments for this person in this window."));
  const file = new File(["BEGIN:VCALENDAR\nVERSION:2.0\nEND:VCALENDAR\n"], "marco.ics", { type: "text/calendar" });
  Object.defineProperty(file, "text", { value: async () => "BEGIN:VCALENDAR\nVERSION:2.0\nEND:VCALENDAR\n" });
  fireEvent.change(form.getByLabelText("Calendar file"), { target: { files: [file] } });
  await form.findByText("Calendar imported. Find a time below.");
  fireEvent.click(form.getByRole("button", { name: "Find a time" }));
  fireEvent.click(form.getByRole("button", { name: "Review assignment" }));
  fireEvent.click(form.getByRole("button", { name: "Confirm assignment & follow-up" }));
  await form.findByText("Assignment saved. In-app follow-up scheduled; completion unchanged.");
  fireEvent.change(form.getByLabelText("Recipient reply"), { target: { value: "Framing confirmed access; I will start then." } });
  fireEvent.click(form.getByRole("button", { name: "Record reply" }));
  expect(form.getByText("Recorded reply: Framing confirmed access; I will start then.")).toBeVisible();
  const saved = JSON.parse(localStorage.getItem(projectStorageKey(model))!);
  expect(saved.coordination.tasks).toHaveLength(1);
  expect(saved.coordination.followUps[0]).toMatchObject({ status: "replied", reply: "Framing confirmed access; I will start then." });
  expect(saved.items.find((item: { id: string }) => item.id === "PLAN-401").status).toBe("none");
  expect(screen.getAllByTestId("shared-building")).toHaveLength(1);
});
