"""models elements jobs

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-04 07:03:24.135257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('ifc_guid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'needs_review', 'done', name='elementstatus', native_enum=False, length=20), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ifc_guid')
    )
    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_elements_project_id'), ['project_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('merge_parent_id', sa.String(length=36), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merge_parent_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'number')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_project_id'), ['project_id'], unique=False)

    op.create_table('element_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('element_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('ifc_class', sa.String(length=80), nullable=False),
    sa.Column('discipline', sa.String(length=30), nullable=False),
    sa.Column('trade', sa.String(length=30), nullable=False),
    sa.Column('level_id', sa.String(length=36), nullable=True),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('props', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('geom_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'element_id')
    )
    with op.batch_alter_table('element_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_element_revisions_discipline'), ['discipline'], unique=False)
        batch_op.create_index(batch_op.f('ix_element_revisions_element_id'), ['element_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_element_revisions_level_id'), ['level_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_element_revisions_trade'), ['trade'], unique=False)
        batch_op.create_index(batch_op.f('ix_element_revisions_version_id'), ['version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_element_revisions_zone_id'), ['zone_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_version_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('current_version_id')

    with op.batch_alter_table('element_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_element_revisions_zone_id'))
        batch_op.drop_index(batch_op.f('ix_element_revisions_version_id'))
        batch_op.drop_index(batch_op.f('ix_element_revisions_trade'))
        batch_op.drop_index(batch_op.f('ix_element_revisions_level_id'))
        batch_op.drop_index(batch_op.f('ix_element_revisions_element_id'))
        batch_op.drop_index(batch_op.f('ix_element_revisions_discipline'))

    op.drop_table('element_revisions')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_project_id'))

    op.drop_table('model_versions')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elements_project_id'))

    op.drop_table('elements')
    # ### end Alembic commands ###
