"""drawing sheets

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04 07:26:43.959797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawing_sheets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('level_id', sa.String(length=36), nullable=True),
    sa.Column('discipline', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('unit_m', sa.Double(), nullable=True),
    sa.Column('units_confirmed', sa.Boolean(), nullable=False),
    sa.Column('transform', sa.JSON(), nullable=False),
    sa.Column('layer_roles', sa.JSON(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('detected_counts', sa.JSON(), nullable=True),
    sa.Column('corrections', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drawing_sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drawing_sheets_level_id'), ['level_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drawing_sheets_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drawing_sheets_project_id'))
        batch_op.drop_index(batch_op.f('ix_drawing_sheets_level_id'))

    op.drop_table('drawing_sheets')
    # ### end Alembic commands ###
