"""progress uploads photos verifications

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-04 07:42:05.000590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('trade', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analysis_status', sa.String(length=20), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'client_uuid')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_zone_id'), ['zone_id'], unique=False)

    op.create_table('photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('phash', sa.String(length=16), nullable=True),
    sa.Column('exif_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gps_lat', sa.Double(), nullable=True),
    sa.Column('gps_lon', sa.Double(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_phash'), ['phash'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_upload_id'), ['upload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photos_zone_id'), ['zone_id'], unique=False)

    op.create_table('verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=True),
    sa.Column('element_id', sa.String(length=36), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('prev_status', sa.String(length=20), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verifications_element_id'), ['element_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_upload_id'), ['upload_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verifications_upload_id'))
        batch_op.drop_index(batch_op.f('ix_verifications_state'))
        batch_op.drop_index(batch_op.f('ix_verifications_project_id'))
        batch_op.drop_index(batch_op.f('ix_verifications_element_id'))

    op.drop_table('verifications')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_zone_id'))
        batch_op.drop_index(batch_op.f('ix_photos_upload_id'))
        batch_op.drop_index(batch_op.f('ix_photos_sha256'))
        batch_op.drop_index(batch_op.f('ix_photos_project_id'))
        batch_op.drop_index(batch_op.f('ix_photos_phash'))

    op.drop_table('photos')
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_zone_id'))
        batch_op.drop_index(batch_op.f('ix_uploads_user_id'))
        batch_op.drop_index(batch_op.f('ix_uploads_project_id'))

    op.drop_table('uploads')
    # ### end Alembic commands ###
